version: '3.9'
services:
  postgresdb:
    image: postgres:16.2
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
      - DATABASE_HOST=${PG_HOST}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/root/redis
      - ./redis_data/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  app:
    image: socio:1.0.0
    container_name: golang_container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DBNAME=${PG_DBNAME}
      - PG_HOST=postgresdb
      - PG_PORT=${PG_PORT}
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
      - redis

volumes:
  pg_data:
  redis_data:
