global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'golang'
    metrics_path: '/api/v1/metrics/'
    static_configs:
      - targets: ['app:8080']
  
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service_container:9096']
  
  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service_container:9099']

  - job_name: 'post_service'
    static_configs:
      - targets: ['post_service_container:9097']
  
  - job_name: 'public_group_service'
    static_configs:
      - targets: ['public_group_service_container:9098']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
