// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package publicgroup

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	domain "socio/domain"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEc7c1227DecodeSocioUsecasePublicGroup(in *jlexer.Lexer, out *PublicGroupWithInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "publicGroup":
			if in.IsNull() {
				in.Skip()
				out.PublicGroup = nil
			} else {
				if out.PublicGroup == nil {
					out.PublicGroup = new(domain.PublicGroup)
				}
				easyjsonEc7c1227DecodeSocioDomain(in, out.PublicGroup)
			}
		case "isSubscribed":
			out.IsSubscribed = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEc7c1227EncodeSocioUsecasePublicGroup(out *jwriter.Writer, in PublicGroupWithInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"publicGroup\":"
		out.RawString(prefix[1:])
		if in.PublicGroup == nil {
			out.RawString("null")
		} else {
			easyjsonEc7c1227EncodeSocioDomain(out, *in.PublicGroup)
		}
	}
	{
		const prefix string = ",\"isSubscribed\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsSubscribed))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PublicGroupWithInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEc7c1227EncodeSocioUsecasePublicGroup(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PublicGroupWithInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEc7c1227EncodeSocioUsecasePublicGroup(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PublicGroupWithInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEc7c1227DecodeSocioUsecasePublicGroup(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PublicGroupWithInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEc7c1227DecodeSocioUsecasePublicGroup(l, v)
}
func easyjsonEc7c1227DecodeSocioDomain(in *jlexer.Lexer, out *domain.PublicGroup) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint(in.Uint())
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "avatar":
			out.Avatar = string(in.String())
		case "subscribersCount":
			out.SubscribersCount = uint(in.Uint())
		case "createdAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEc7c1227EncodeSocioDomain(out *jwriter.Writer, in domain.PublicGroup) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"avatar\":"
		out.RawString(prefix)
		out.String(string(in.Avatar))
	}
	{
		const prefix string = ",\"subscribersCount\":"
		out.RawString(prefix)
		out.Uint(uint(in.SubscribersCount))
	}
	if true {
		const prefix string = ",\"createdAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	if true {
		const prefix string = ",\"updatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}
