name: Go

on:
  push:
    branches: [ main, dev, VKP-74-ci ]
  pull_request:
    branches: [ main, dev, VKP-74-ci ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: ^1.22

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get ./...

    - name: Run make test
      run: make test

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1

    - name: Run golangci-lint
      run: golangci-lint run ./...
